name: ${name}
version: ${version}
main: ${pluginMainClass}
commands:
  novswar:
    description: Base NovsWar command
    usage: /<command> [options]
    permission: novswar.command
  nw:
    description: Base NovsWar command
    usage: /<command> [options]
    permission: novswar.command